---
# handlers file for flask-app
- name: restart nginx
  service: "name=nginx state=restarted"
  become: true
  notify: run app

- name: run app
  command: make run
  args:
    chdir: /usr/src/app/terraform-packer-ansible-demo/apps/flask-app
  become: true
