---
# defaults file for docker
docker_group_members:
  - 'ubuntu'

docker_apt_release_channel:
  'stable'

docker_apt_arch:
  amd64

docker_apt_repository:
  "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} {{docker_apt_release_channel}}"
