---
# tasks file for nginx

- name: Install nginx
  apt: name=nginx state=present
  register: nginx

- name: Remove default nginx config
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Install system nginx config
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Restart nginx
  service: name=nginx state=restarted
  when: nginx is success
  changed_when: false
