---
- name: Check if old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
    state: absent
  become: true

- name: Install Docker dependencies.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present
  become: true

- name: add docker repo apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  become: true
  ignore_errors: true

- name: Ensure curl is present (on older systems without SNI).
  package: name=curl state=present
  become: true
  when: add_repository_key is failed

- name: Add Docker apt key (alternative)
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
    warn: false
  become: true
  when: add_repository_key is failed

- name: 'add Docker repository'
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
  become: true

- name: Install Docker.
  package:
    name: "docker-ce"
    state: "present"
  become: true
  notify: restart docker
